name: SDK CI

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
  push:
    branches: [main, master]

permissions:
  contents: read

jobs:
  # Check for lint issues
  lint:
    name: Test & Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out the current branch
        uses: actions/checkout@v6

      # Execute unit tests.
      - name: Run unit tests
        run: ./gradlew zero_bounce_sdk:testDebugUnitTest

      # Build a debug version to test that the sdk compiles.
      - name: Generate release build
        run: ./gradlew :zero_bounce_sdk:assembleDebug
